### ISSUE TITLE
Support of JSShaper

### ISSUE THREAD

**Issue by ghost** [olov/jsshaper#9]
When will support of ES6 in JSShaper?

**Comment by olov** [comment]
Never, I think. JSShaper is not maintained any longer. My latest commit happened in 2012 and I don't plan to make any future changes to it. I created JSShaper out of necessity because I needed a tool for doing source code transformations for restrict mode. At the time there wasn't anything else available out there (to my knowledge). Even JavaScript-in-JavaScript parsers were uncommon (Esprima and Acorn had not been written yet). I hope JSShaper managed to give some inspiration to other authors in terms of what source-to-source transformations enables and in particular how to do it non-destructively, while still being very fast.
